name: deploy

on:
  release:
    types: [published, prereleased]

jobs:
  deploy:
    name: tag deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node_modules
        run: cd client/ && pwd && yarn install
      - name: App Build
        run: cd client/ && pwd && yarn build
